<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error handling</title>
</head>
<body>
    <script>
        class MathUtil{ //public class
            static sum (...numbers){ //static method

                if (numbers.length===0){
                    throw new Error ("Total Parameter harus lebih dari 0"); //membuat pesan error
                }

                let total = 0; //variabel
                for(const number of numbers){//perulangan for of
                    total += number;
                }
                return total;
            }
        }

        
        try{
            console.info(MathUtil.sum()); //memanggil sum tanpa parameter (harusnya error namun karena ditangani oleh try catch hanya muncul pesan saja)
            console.info("hai");
        }catch(error){ //catch dijalankan ketika kode pata try mengalami error
            console.info(`Terjadi Error : ${error.message}`);//menampilkan pesan error yang telah dibuat
        }finally{ //kode akan dijalankan entah try catch mengalami error ataupun tidak
            console.info("program selesai");
        }

        //finally tanpa catch lebih ke bukan penanganan error tapi bisa digunakan pada kasus tertentu
        class Counter{
            #counter = 1;

            next(){
                try{
                    return this.#counter;
                }finally{
                    this.#counter++;
                }
            }
        }

        const counter = new Counter();
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        
    </script>
</body>
</html>